global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector-telemetry'
    static_configs:
      - targets: ['otel-collector:8888'] # <— otelcol_* metryki

  - job_name: 'otel-collector-exporter'
    static_configs:
      - targets: ['otel-collector:9464'] # <— metryki przekonwertowane z Twojej appki

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
